
T5439.hs:83:33:
    Couldn't match expected type `Attempt (WaitOpResult (WaitOps rs))'
                with actual type `Attempt (HNth n0 l0) -> Attempt (HElemOf l0)'
    Relevant bindings include
      registerWaitOp :: WaitOps rs
                        -> f (Attempt (WaitOpResult (WaitOps rs))) -> IO Bool
        (bound at T5439.hs:62:3)
      ops :: WaitOps rs (bound at T5439.hs:62:18)
      ev :: f (Attempt (WaitOpResult (WaitOps rs)))
        (bound at T5439.hs:62:22)
      register :: Bool -> Peano n -> WaitOps (HDrop n rs) -> IO Bool
        (bound at T5439.hs:65:9)
    In the second argument of `($)', namely
      `inj $ Failure (e :: SomeException)'
    In a stmt of a 'do' block:
      c <- complete ev $ inj $ Failure (e :: SomeException)
    In the expression:
      do { c <- complete ev $ inj $ Failure (e :: SomeException);
           return $ c || not first }

T5439.hs:83:39:
    Couldn't match expected type `Peano n0'
                with actual type `Attempt Î±0'
    In the return type of a call of `Failure'
    In the second argument of `($)', namely
      `Failure (e :: SomeException)'
    In the second argument of `($)', namely
      `inj $ Failure (e :: SomeException)'
